common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from views import base_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('theone/', include('theone.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

theone/urls.py
from django.urls import path
from views import base_views

app_name = 'theone'

urlpatterns = [
    #base_views.py
    path('',base_views.index, name='index'),
    path('theone/<int:gu_id>/', base_views.detail, name='detail'),
]

common/models.py
from django.db import models

# Create your models here.

theone/models.py
from django.db import models

class Seoul(models.Model):
     subject = models.CharField(max_length=200)
     content = models.TextField()
     create_Date = models.DateTimeField()


# #종로구
# class Jongnogu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #중구
# class Junggu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #용산구
# class Yongsangu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #성동구
# class Seongdonggu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #광진구
# class Gwangjingu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #동대문구
# class Dongdaemungu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #중랑구
# class Jungnanggu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #성북구
# class Seongbukgu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #강북구
# class Gangbukgu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #도봉구
# class Dobonggu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #노원구
# class Nowongu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #은평구
# class Eunpyeonggu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #서대문구
# class Seodaemungu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #마포구
# class Mapogu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #양천구
# class Yangcheongu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #강서구
# class Gangseogu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #구로구
# class Gurogu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()
    
# #금천구
# class Geumcheongu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #영등포구
# class Yeongdeungpogu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #동작구
# class Dongjakgu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #관악구
# class Gwanakgu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #서초구
# class Seochogu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #강남구
# class Gangnamgu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #송파구
# class Songpagu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField()

# #강동구
# class Gangdonggu(models.Model):
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     create_Date = models.DateTimeField() 

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

theone/forms.py
from django import forms
from django import forms
# from theone.models import Seoul

# class GuForm(forms.ModelForm):
#     class meta:
#         model = Seoul
#         fields = ['subject', 'content']

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

views/base_views.py
from operator import truth
from django.shortcuts import redirect, render, get_object_or_404
from theone.models import Seoul


def index(request):
    gu_list = Seoul.objects.order_by('create_Date')
    context = {'gu_list': gu_list}
    if request.user.is_authenticated:
        return render(request, 'theone/search.html',context)
    else:
        return render(request, 'common/login.html')
    
def detail(request, gu_id):
    gu = get_object_or_404(Seoul, pk=gu_id)
    context = {'gu': gu}
    return render(request, 'theone/gu_detail.html',context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- theone CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>TheOne</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">PW</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">아이디</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">가입</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'theone:index' %}"><img src="http://localhost:8000/static/image/logo.png" alt="TheOne" width="140", height="80"></a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{user.username}} 로그아웃</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/theone/gu_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ gu.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ gu.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ gu.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <form action="{% url 'theone:detail' gu.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/theone/search.html
{% extends 'base.html' %}
{% block content %}
    <table class="search">
        <head>
            <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
            <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
            <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
            <div class="container">
                <div class="row">
                       <div id="custom-search-input">
                                        <div class="input-group col-md-4 col-md-offset-4">
                                            <input type="text" class="  search-query form-control" placeholder="Search" />
                                            <span class="input-group-btn">
                                                <button class="btn btn-danger" type="button">
                                                    <span class=" glyphicon glyphicon-search"></span>
                                                </button>
                                            </span>
                                        </div>
                                    </div>
                </div>
            </div>
        </head>
        <body>
        {% if gu_list %}
        {% for gu in gu_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'theone:detail' gu_id=gu.id %}">{{ gu.subject }}</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </body>
    </table>
</div>
{% endblock %}